function splitPair(pro_txt)
%to split pro(galgin image, pro image,label) to (galgin image,label) ...
%  and (pro image,label) for training network.
%input:
%  pro_txt     --pro txt generated by makePosPair.m or makeNegPair.m
%
%output:
%      two txt  --One is (galgin image,label), another is (pro image,label)
%
%Jun Hu
%2017-4
fid=fopen(pro_txt,'rt');
list=textscan(fid,'%s %s %d');
fclose(fid);
gal=list{1};pro=list{2};label=list{3};
fid=fopen([pro_txt '-gal'],'wt');
for i=1:length(gal)
 fprintf(fid,'%s %d\n',gal{i},label(i));
end
fclose(fid);
fid=fopen([pro_txt '-pro'],'wt');
for i=1:length(gal)
 fprintf(fid,'%s %d\n',pro{i},label(i));
end
fclose(fid);
end
